apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa
namePrefix: qa-

resources:
- ../../base

components:
  - ../../variants/non-prod

# patchesStrategicMerge:
# - deployment.yml
# - version.yml
# - settings.yml
# - service.yml

patches:
- path: deployment.yml
- path: version.yml
- path: settings.yml
- path: service.yml