apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base

components:
  - ../../variants/prod

# patchesStrategicMerge:
# - deployment.yml
# - version.yml
# - replicas.yml
# - settings.yml
# - service.yml

patches:
- path: deployment.yml
- path: version.yml
- path: replicas.yml
- path: settings.yml
- path: service.yml
